<a href="https://colab.research.google.com/github/yusrasheikh963-debug/Countries-Dataset-Assi15/blob/main/Datasets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import files
upload = files.upload()

Saving Countries.csv to Countries (1).csv

In [ ]:
filepath = '/content/countries.csv'

In [ ]:
df = pd.read_csv("countries.csv")
df

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.000000,65.000000,383560.0,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.000000,20.000000,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.000000,3.000000,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.500000,1.500000,187.2,...,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.500000,18.500000,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,Vietnam,Socialist Republic of Vietnam,Vietnamese dong,Hanoi,South-Eastern Asia,Asia,Vietnamese,16.166667,107.833333,123600.0,...,98186856,30.26050,60123739,38063117,1.04,3.08,Authoritarian,28.4,Nguyễn Phú Trọng,General Secretary of the Communist Party
190,West Bank and Gaza,West Bank and Gaza,Israeli new shekel,Ramallah,Western Asia,Asia,Palestinian,31.900000,35.200000,4449.0,...,5043612,NaN,1145354,3898258,1.75,4.39,Hybrid regime,15.4,NaN,NaN
191,Yemen,Republic of Yemen,Yemeni rial,Sana'a,Western Asia,Asia,Yemeni,15.000000,48.000000,234520.0,...,33696614,0.00000,20491585,13205029,1.27,1.95,Authoritarian,14.8,Abdrabbuh Mansur Hadi,President
192,Zambia,Republic of Zambia,New Zambian kwacha,Lusaka,Eastern Africa,Africa,Zambian,-15.000000,30.000000,238360.0,...,20017675,15.06020,10857387,9160288,2.15,5.61,Hybrid regime,13.2,Edgar Lungu,President
193,Zimbabwe,Republic of Zimbabwe,U.S. dollar,Harare,Eastern Africa,Africa,Zimbabwean,-20.000000,30.000000,162000.0,...,16320537,30.56600,11033499,5287038,1.85,3.16,Authoritarian,14.2,Emmerson Mnangagwa,President

In [ ]:
df.columns

Index(['country', 'country_long', 'currency', 'capital_city', 'region',
       'continent', 'demonym', 'latitude', 'longitude', 'agricultural_land',
       'forest_area', 'land_area', 'rural_land', 'urban_land',
       'central_government_debt_pct_gdp', 'expense_pct_gdp', 'gdp',
       'inflation', 'self_employed_pct', 'tax_revenue_pct_gdp',
       'unemployment_pct', 'vulnerable_employment_pct',
       'electricity_access_pct', 'alternative_nuclear_energy_pct',
       'electricty_production_coal_pct',
       'electricty_production_hydroelectric_pct',
       'electricty_production_gas_pct', 'electricty_production_nuclear_pct',
       'electricty_production_oil_pct', 'electricty_production_renewable_pct',
       'energy_imports_pct', 'fossil_energy_consumption_pct',
       'renewable_energy_consumption_pct', 'co2_emissions',
       'methane_emissions', 'nitrous_oxide_emissions',
       'greenhouse_other_emissions', 'urban_population_under_5m',
       'health_expenditure_pct_gdp', 'health_expenditure_capita',
       'hospital_beds', 'hiv_incidence', 'suicide_rate', 'armed_forces',
       'internally_displaced_persons', 'military_expenditure_pct_gdp',
       'birth_rate', 'death_rate', 'fertility_rate', 'internet_pct',
       'life_expectancy', 'net_migration', 'population_female',
       'population_male', 'population', 'women_parliament_seats_pct',
       'rural_population', 'urban_population', 'press', 'democracy_score',
       'democracy_type', 'median_age', 'political_leader', 'title'],
      dtype='object')

In [ ]:
df.head()

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.0,65.0,383560.0,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.0,20.0,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.0,3.0,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.5,1.5,187.2,...,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.5,18.5,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President

In [ ]:
df.tail()

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
189,Vietnam,Socialist Republic of Vietnam,Vietnamese dong,Hanoi,South-Eastern Asia,Asia,Vietnamese,16.166667,107.833333,123600.0,...,98186856,30.2605,60123739,38063117,1.04,3.08,Authoritarian,28.4,Nguyễn Phú Trọng,General Secretary of the Communist Party
190,West Bank and Gaza,West Bank and Gaza,Israeli new shekel,Ramallah,Western Asia,Asia,Palestinian,31.900000,35.200000,4449.0,...,5043612,NaN,1145354,3898258,1.75,4.39,Hybrid regime,15.4,NaN,NaN
191,Yemen,Republic of Yemen,Yemeni rial,Sana'a,Western Asia,Asia,Yemeni,15.000000,48.000000,234520.0,...,33696614,0.0000,20491585,13205029,1.27,1.95,Authoritarian,14.8,Abdrabbuh Mansur Hadi,President
192,Zambia,Republic of Zambia,New Zambian kwacha,Lusaka,Eastern Africa,Africa,Zambian,-15.000000,30.000000,238360.0,...,20017675,15.0602,10857387,9160288,2.15,5.61,Hybrid regime,13.2,Edgar Lungu,President
193,Zimbabwe,Republic of Zimbabwe,U.S. dollar,Harare,Eastern Africa,Africa,Zimbabwean,-20.000000,30.000000,162000.0,...,16320537,30.5660,11033499,5287038,1.85,3.16,Authoritarian,14.2,Emmerson Mnangagwa,President

In [ ]:
df.tail(5)

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
189,Vietnam,Socialist Republic of Vietnam,Vietnamese dong,Hanoi,South-Eastern Asia,Asia,Vietnamese,16.166667,107.833333,123600.0,...,98186856,30.2605,60123739,38063117,1.04,3.08,Authoritarian,28.4,Nguyễn Phú Trọng,General Secretary of the Communist Party
190,West Bank and Gaza,West Bank and Gaza,Israeli new shekel,Ramallah,Western Asia,Asia,Palestinian,31.900000,35.200000,4449.0,...,5043612,NaN,1145354,3898258,1.75,4.39,Hybrid regime,15.4,NaN,NaN
191,Yemen,Republic of Yemen,Yemeni rial,Sana'a,Western Asia,Asia,Yemeni,15.000000,48.000000,234520.0,...,33696614,0.0000,20491585,13205029,1.27,1.95,Authoritarian,14.8,Abdrabbuh Mansur Hadi,President
192,Zambia,Republic of Zambia,New Zambian kwacha,Lusaka,Eastern Africa,Africa,Zambian,-15.000000,30.000000,238360.0,...,20017675,15.0602,10857387,9160288,2.15,5.61,Hybrid regime,13.2,Edgar Lungu,President
193,Zimbabwe,Republic of Zimbabwe,U.S. dollar,Harare,Eastern Africa,Africa,Zimbabwean,-20.000000,30.000000,162000.0,...,16320537,30.5660,11033499,5287038,1.85,3.16,Authoritarian,14.2,Emmerson Mnangagwa,President

In [ ]:
df.shape

(194, 64)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Data columns (total 64 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   country                                  194 non-null    object
 1   country_long                             194 non-null    object
 2   currency                                 194 non-null    object
 3   capital_city                             194 non-null    object
 4   region                                   194 non-null    object
 5   continent                                194 non-null    object
 6   demonym                                  194 non-null    object
 7   latitude                                 194 non-null    float64
 8   longitude                                194 non-null    float64
 9   agricultural_land                        193 non-null    float64
 10  forest_area                              194 non-null    float64
 11  land_area                                194 non-null    float64
 12  rural_land                               194 non-null    float64
 13  urban_land                               194 non-null    float64
 14  central_government_debt_pct_gdp          120 non-null    float64
 15  expense_pct_gdp                          156 non-null    float64
 16  gdp                                      193 non-null    float64
 17  inflation                                184 non-null    float64
 18  self_employed_pct                        179 non-null    float64
 19  tax_revenue_pct_gdp                      159 non-null    float64
 20  unemployment_pct                         179 non-null    float64
 21  vulnerable_employment_pct                179 non-null    float64
 22  electricity_access_pct                   194 non-null    float64
 23  alternative_nuclear_energy_pct           138 non-null    float64
 24  electricty_production_coal_pct           138 non-null    float64
 25  electricty_production_hydroelectric_pct  138 non-null    float64
 26  electricty_production_gas_pct            138 non-null    float64
 27  electricty_production_nuclear_pct        138 non-null    float64
 28  electricty_production_oil_pct            138 non-null    float64
 29  electricty_production_renewable_pct      138 non-null    float64
 30  energy_imports_pct                       138 non-null    float64
 31  fossil_energy_consumption_pct            168 non-null    float64
 32  renewable_energy_consumption_pct         192 non-null    float64
 33  co2_emissions                            191 non-null    float64
 34  methane_emissions                        191 non-null    float64
 35  nitrous_oxide_emissions                  191 non-null    float64
 36  greenhouse_other_emissions               184 non-null    float64
 37  urban_population_under_5m                194 non-null    float64
 38  health_expenditure_pct_gdp               190 non-null    float64
 39  health_expenditure_capita                190 non-null    float64
 40  hospital_beds                            192 non-null    float64
 41  hiv_incidence                            133 non-null    float64
 42  suicide_rate                             183 non-null    float64
 43  armed_forces                             174 non-null    float64
 44  internally_displaced_persons             73 non-null     float64
 45  military_expenditure_pct_gdp             163 non-null    float64
 46  birth_rate                               194 non-null    float64
 47  death_rate                               194 non-null    float64
 48  fertility_rate                           193 non-null    float64
 49  internet_pct                             194 non-null    float64
 50  life_expectancy                          191 non-null    float64
 51  net_migration                            194 non-null    int64
 52  population_female                        194 non-null    int64
 53  population_male                          194 non-null    int64
 54  population                               194 non-null    int64
 55  women_parliament_seats_pct               193 non-null    float64
 56  rural_population                         194 non-null    int64
 57  urban_population                         194 non-null    int64
 58  press                                    194 non-null    float64
 59  democracy_score                          194 non-null    float64
 60  democracy_type                           194 non-null    object
 61  median_age                               194 non-null    float64
 62  political_leader                         187 non-null    object
 63  title                                    187 non-null    object
dtypes: float64(48), int64(6), object(10)
memory usage: 97.1+ KB

In [ ]:
df.describe()

,latitude,longitude,agricultural_land,forest_area,land_area,rural_land,urban_land,central_government_debt_pct_gdp,expense_pct_gdp,gdp,...,net_migration,population_female,population_male,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,median_age
count,194.000000,194.000000,1.930000e+02,1.940000e+02,1.940000e+02,1.940000e+02,194.000000,120.000000,156.000000,1.930000e+02,...,194.000000,1.940000e+02,1.940000e+02,1.940000e+02,193.000000,1.940000e+02,1.940000e+02,194.000000,194.000000,194.000000
mean,18.975601,22.027491,2.454551e+05,2.086784e+05,6.675087e+05,6.563711e+05,9777.116531,66.759366,30.051403,5.144851e+11,...,-51.407216,2.028316e+07,2.050572e+07,4.078888e+07,25.022994,1.763322e+07,2.315566e+07,2.539330,4.644536,25.661856
std,23.876225,66.396389,6.356268e+05,7.824926e+05,1.837107e+06,1.811169e+06,42301.458421,71.806247,26.740880,2.307148e+12,...,94525.968598,7.258941e+07,7.607158e+07,1.486470e+08,12.671044,7.664187e+07,7.940393e+07,1.800128,2.818297,9.415569
min,-41.000000,-175.000000,4.000000e+00,0.000000e+00,2.027000e+00,3.495450e-02,0.000000,0.000000,0.000267,6.034940e+07,...,-525116.000000,5.513000e+03,5.799000e+03,1.131200e+04,0.000000,0.000000e+00,5.717000e+03,0.000000,0.000000,10.500000
25%,4.000000,-5.000000,6.464000e+03,3.331775e+03,2.355250e+04,2.186562e+04,359.618250,31.951300,18.371875,1.181390e+10,...,-12242.250000,1.036218e+06,1.044902e+06,2.106358e+06,15.384600,5.896640e+05,1.222244e+06,1.525000,2.722500,16.950000
50%,16.583333,21.500000,3.872780e+04,2.528925e+04,1.203750e+05,1.159945e+05,1645.170000,55.426850,27.337750,4.115390e+10,...,-970.000000,4.502713e+06,4.450049e+06,9.125614e+06,25.252500,2.512382e+06,4.508837e+06,2.400000,5.050000,24.950000
75%,40.000000,50.162500,2.150000e+05,1.236735e+05,5.237000e+05,4.911505e+05,4054.022500,79.539300,35.083500,2.519450e+11,...,2904.250000,1.526606e+07,1.478872e+07,3.031361e+07,33.636400,1.133354e+07,1.621355e+07,2.925000,6.967500,34.050000
max,65.000000,178.000000,5.285080e+06,8.153120e+06,1.637690e+07,1.622420e+07,522345.000000,687.994000,310.443000,2.546270e+13,...,561580.000000,6.915285e+08,7.311805e+08,1.417173e+09,61.250000,9.088048e+08,8.975784e+08,10.000000,9.870000,50.500000

In [ ]:
df.dtypes

country              object
country_long         object
currency             object
capital_city         object
region               object
                     ...
democracy_score     float64
democracy_type       object
median_age          float64
political_leader     object
title                object
Length: 64, dtype: object

In [ ]:
df.isnull().sum()

country             0
country_long        0
currency            0
capital_city        0
region              0
                   ..
democracy_score     0
democracy_type      0
median_age          0
political_leader    7
title               7
Length: 64, dtype: int64

In [ ]:
df.nunique()

country             194
country_long        194
currency            142
capital_city        194
region               22
                   ...
democracy_score     146
democracy_type        5
median_age          143
political_leader    187
title                17
Length: 64, dtype: int64

In [ ]:
df.sample()

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.0,3.0,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.5,Authoritarian,24.0,Abdelmadjid Tebboune,President

In [ ]:
df.sample(4)

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
92,Latvia,Republic of Latvia,Euro,Riga,Northern Europe,Europe,Latvian,57.000000,25.000000,19690.0,...,1883379,30.0000,592511,1290868,4.00,7.38,Flawed democracy,39.8,Krišjānis Kariņš,Prime Minister
160,St. Lucia,St. Lucia,East Caribbean dollar,Castries,Caribbean,Americas,Saint Lucian,13.883333,-60.966667,99.4,...,179857,11.1111,145594,34263,0.00,0.00,Unknown,29.5,NaN,NaN
28,Cambodia,Kingdom of Cambodia,Cambodian riel,Phnom Penh,South-Eastern Asia,Asia,Cambodian,13.000000,105.000000,57890.0,...,16767842,20.8000,12556766,4211076,1.70,3.59,Authoritarian,22.7,Hun Sen,Prime Minister
52,El Salvador,Republic of El Salvador,U.S. dollar,San Salvador,Central America,Americas,Salvadoran,13.833333,-88.916667,11957.0,...,6336392,27.3810,1598862,4737530,2.62,5.96,Hybrid regime,22.8,Nayib Bukele,President

In [ ]:
df.value_counts()

country          country_long                                currency                   capital_city    region              continent  demonym      latitude    longitude    agricultural_land  forest_area  land_area  rural_land  urban_land  central_government_debt_pct_gdp  expense_pct_gdp  gdp           inflation  self_employed_pct  tax_revenue_pct_gdp  unemployment_pct  vulnerable_employment_pct  electricity_access_pct  alternative_nuclear_energy_pct  electricty_production_coal_pct  electricty_production_hydroelectric_pct  electricty_production_gas_pct  electricty_production_nuclear_pct  electricty_production_oil_pct  electricty_production_renewable_pct  energy_imports_pct  fossil_energy_consumption_pct  renewable_energy_consumption_pct  co2_emissions  methane_emissions  nitrous_oxide_emissions  greenhouse_other_emissions  urban_population_under_5m  health_expenditure_pct_gdp  health_expenditure_capita  hospital_beds  hiv_incidence  suicide_rate  armed_forces  internally_displaced_persons  military_expenditure_pct_gdp  birth_rate  death_rate  fertility_rate  internet_pct  life_expectancy  net_migration  population_female  population_male  population  women_parliament_seats_pct  rural_population  urban_population  press  democracy_score  democracy_type    median_age  political_leader             title
Azerbaijan       Republic of Azerbaijan                      New Azeri manat            Baku            Western Asia        Asia       Azerbaijani   40.500000   47.500000   47801.00           11317.7      82646.0    82218.70    2589.860    16.82240                         27.14440         7.872110e+10  13.85230   66.2843            13.42130             5.462             54.46420                   100.0000                0.572046                        0.000000                        6.630750                                 86.082300                      0.00000                            6.509240                       0.409106                             -310.38500          98.36600                       1.23                              34305.0        15733.100          4793.550                 -514.235                    0.000000                   4.60677                     191.2270                   4.82           0.03           4.1           82000.0       659000.0                      5.270060                      11.100      7.600       1.520           86.0000       69.0              1084          5154492            5020523          10175016    18.33330                    4357959           5817057           1.32   2.65             Authoritarian     27.9        Ilham Aliyev                 President                            1
Bangladesh       People's Republic of Bangladesh             Bangladeshi taka           Dhaka           Southern Asia       Asia       Bangladeshi   24.000000   90.000000   99010.00           18834.0      130170.0   79328.90    56970.000   31.20450                         8.32425          4.602010e+11  7.69695    59.0319            7.64236              4.699             53.67380                   98.9910                 0.153500                        1.689520                        0.959143                                 80.703600                      0.00000                            16.380000                      0.267747                              16.84170           73.76890                       27.96                             85493.1        88904.000          28076.800                 1513.770                   6.064840                   2.62801                     50.6641                    0.79           0.01           3.7           227000.0      427000.0                      1.269780                      17.821      5.680       1.981           38.9174       72.0             -174500        86327159           84859213         171186372   20.85710                    103206552         67979820          1.54   5.57             Hybrid regime     22.7        Sheikh Hasina                Prime Minister                       1
Bolivia          Plurinational State of Bolivia              Bolivian Boliviano         Sucre           South America       Americas   Bolivian     -17.000000  -65.000000   377870.00          508338.0     1083300.0  1059510.00  1767.520    68.33990                         21.81100         4.306890e+10  1.74633    69.1160            16.96490             4.419             66.02310                   98.5562                 1.974980                        0.000000                        28.881300                                66.346200                      0.00000                            2.251410                       2.521110                             -177.98600          84.15330                       16.86                             18375.3        26597.800          9838.140                  2436.270                   0.000000                   7.85706                     241.1180                   1.29           0.13           6.2           71000.0       31.0                          1.544460                      21.836      9.945       2.618           65.9774       64.0             -4666          6097747            6126364          12224110    46.15380                    3565773           8658337           2.21   5.70             Hybrid regime     20.1        Jeanine Áñez                 President                            1
Brazil           Federative Republic of Brazil               Brazilian real             Brasília        South America       Americas   Brazilian    -10.000000  -55.000000   2368790.00         4966200.0    8358140.0  8385500.00  45853.300   86.09500                         32.19910         1.920100e+12  9.28011    35.0868            14.31680             9.461             30.68230                   99.4621                 10.809100                       4.722410                        61.848500                                13.666200                      2.60357                            5.044250                       12.118400                             11.87010           59.10750                       50.05                             414139.0       449214.000         191103.000               -12454.900                  1.741760                   10.31290                    700.7130                   2.09           0.24           6.9           762000.0      5600.0                        1.190810                      12.883      8.326       1.641           80.6900       73.0              20376         109580471          105733027        215313498   17.73880                    26795765          188517733         2.38   6.97             Flawed democracy  29.2        Jair Bolsonaro               President                            1
Cameroon         Republic of Cameroon                        Central African CFA franc  Yaoundé         Middle Africa       Africa     Cameroonian   6.000000    12.000000   97500.00           203405.0     472710.0   463837.00   2352.110    79.45770                         12.06030         4.434160e+10  6.24768    75.2360            10.87060             4.001             72.32580                   65.4467                 4.600760                        0.000000                        74.992600                                5.992900                       0.00000                            17.889900                      1.124590                             -28.31980           38.31790                       78.94                             9928.4         17797.700          62399.500                 1385.670                   1.916620                   3.76583                     58.0053                    1.30           0.56           9.0           34000.0       987000.0                      1.024090                      34.938      8.582       4.463           45.6022       60.0             -9889          13992014           13922522         27914536    33.88890                    11519492          16395044          1.81   3.28             Authoritarian     13.6        Paul Biya                    President                            1
Colombia         Republic of Colombia                        Colombian peso             Bogotá          South America       Americas   Colombian     4.000000   -72.000000   482428.00          591419.0     1109500.0  1127200.00  5114.560    79.78410                         34.95670         3.439390e+11  10.17720   50.9077            14.44340             10.726            47.57390                   99.9991                 9.203540                        11.852200                       64.959400                                19.343100                      0.00000                            0.567976                       3.277450                             -274.13300          76.68570                       31.31                             79057.6        77156.400          23778.200                 11462.400                  1.780240                   8.99294                     477.2750                   1.71           0.17           3.9           481000.0      4766000.0                     3.401890                      14.204      7.735       1.717           73.0284       73.0              211978        26298417           25575607         51874024    28.87700                    9311387           42562637          1.83   6.96             Flawed democracy  27.2        Iván Duque                   President                            1
Congo            Republic of Congo                           Central African CFA franc  Brazzaville     Middle Africa       Africa     Congolese    -1.000000    15.000000   106280.00          219460.0     341500.0   340341.00   420.263     25.48270                         19.46790         1.461550e+10  3.04344    76.2354            9.10708              21.795            75.27940                   49.6572                 1.428710                        0.000000                        53.344900                                46.655100                      0.00000                            0.000000                       0.000000                             -496.59800          40.48060                       71.88                             7153.9         9957.260           1610.020                 -1372.300                   0.711295                   4.46762                     80.8084                    1.60           2.39           6.5           0.0           27000.0                       2.912710                      30.691      7.063       4.171           8.6500        64.0             -4466          2988624            2981800          5970424     14.56950                    1866593           4103831           2.17   3.31             Authoritarian     14.3        Denis Sassou Nguesso         President                            1
Croatia          Republic of Croatia                         Croatian kuna              Zagreb          Southern Europe     Europe     Croatian      45.166667   15.500000   15050.00           19391.1      55960.0    54777.10    1648.410    687.99400                        310.44300        7.096460e+10  10.78060   12.8363            152.18000            6.746             7.32646                    100.0000                11.943800                       20.555300                       56.869500                                10.651400                      0.00000                            1.966540                       9.957290                              45.85970           70.70370                       32.37                             15626.9        3668.680           1773.060                 -2048.190                   2.441130                   7.76502                     1094.5300                  5.54           0.02           16.4          18000.0       2100.0                        2.735570                      9.400       16.200      1.620           81.2540       76.0             -10402         1976858            1877142          3854000     31.78810                    1610240           2243760           2.69   6.57             Flawed democracy  40.0        Andrej Plenković             Prime Minister                       1
Cyprus           Republic of Cyprus                          Euro                       Nicosia         Southern Europe     Europe     Cypriot       35.000000   33.000000   1341.29            1725.3       9240.0     8747.63     518.980     91.66830                         41.22370         2.843910e+10  8.39548    12.1175            24.11230             6.976             10.28340                   100.0000                5.226960                        0.000000                        0.000000                                 0.000000                       0.00000                            91.219900                      8.780060                              94.02670           92.90620                       15.02                             6771.8         749.703            371.658                   577.573                    2.565150                   8.09348                     2245.3600                  3.40           0.04           3.6           16000.0       246000.0                      1.986810                      10.313      7.257       1.321           90.7595       81.0              1995          624713             626775           1251488     14.28570                    414105            837383            3.60   7.59             Flawed democracy  34.1        Nicos Anastasiades           President                            1
Côte d'Ivoire    Republic of Côte d'Ivoire                   West African CFA franc     Yamoussoukro    Western Africa      Africa     Ivorian       8.000000   -5.000000    212000.00          28367.1      318000.0   318024.00   2981.960    171.06500                        16.60170         7.001870e+10  5.27617    72.5864            12.55910             2.637             71.01930                   71.1368                 0.794777                        0.000000                        15.520600                                78.050700                      0.00000                            5.223280                       1.205370                              7.07754            26.49230                       63.34                             10894.9        7980.370           3544.210                  2083.510                   2.719800                   3.72246                     85.1743                    0.40           0.21           8.9           134000.0      302000.0                      1.251480                      33.934      9.001       4.418           45.4255       59.0             -21000         13944972           14215570         28160542    14.17320                    13330919          14829623          2.65   4.15             Hybrid regime     13.8        Alassane Ouattara            President                            1
Dem. Rep. Congo  Democratic Republic of the Congo            Congolese franc            Kinshasa        Middle Africa       Africa     Congolese     0.000000    25.000000   335720.00          1261550.0    2267050.0  2295900.00  7232.350    152.18700                        11.49830         5.806600e+10  2.88585    80.6942            10.70410             4.987             78.16510                   20.7682                 2.359950                        0.000000                        99.709200                                0.044733                       0.00000                            0.134198                       0.111832                              1.95927            5.35581                        96.16                             3025.6         35684.200          14960.600                -2774.770                   0.003635                   4.05093                     21.2539                    0.80           0.18           6.7           134000.0      5686000.0                     0.561686                      42.049      9.700       6.156           22.9016       59.0             -64643         49892177           49118035         99010212    12.80000                    52636799          46373413          1.51   1.49             Authoritarian     11.7        Félix Tshisekedi             President                            1
El Salvador      Republic of El Salvador                     U.S. dollar                San Salvador    Central America     Americas   Salvadoran    13.833333  -88.916667   11957.00           5838.8       20720.0    18676.40    1559.870    65.54800                         29.09860         3.248870e+10  7.19862    37.8640            19.41680             3.822             33.98200                   97.8900                 6.309290                        0.000000                        22.591400                                0.000000                       0.00000                            42.177300                      35.231300                             49.23550           48.42960                       23.70                             6376.3         3269.500           1015.750                  616.234                    0.260808                   9.85178                     385.7430                   1.20           0.17           6.1           42000.0       52000.0                       1.374900                      16.025      8.661       1.803           62.8803       71.0             -27343         3319856            3016535          6336392     27.38100                    1598862           4737530           2.62   5.96             Hybrid regime     22.8        Nayib Bukele                 President                            1
Ethiopia         Federal Democratic Republic of Ethiopia     Ethiopian birr             Addis Ababa     Eastern Africa      Africa     Ethiopian     8.000000    38.000000   384761.00          170685.0     1128570.0  1124620.00  5760.660    31.44880                         8.41227          1.267830e+11  26.83950   85.6278            6.19630              4.018             85.19100                   54.1884                 1.183670                        0.000000                        92.689500                                0.000000                       0.00000                            0.038325                       7.272200                              5.92631            6.56981                        89.52                             18098.0        94645.600          53761.300                 5071.140                   0.000000                   3.48096                     28.6967                    0.33           0.12           5.4           138000.0      3852000.0                     0.527828                      32.383      6.776       4.159           16.6981       65.0             -1391          61399749           61980175         123379924   41.48940                    95420799          27959125          2.23   3.35             Authoritarian     14.7        Abiy Ahmed                   Prime Minister                       1